language: java
jdk:
- oraclejdk8
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — loklak-server-922b0 — token $1/YMh-Vm-YpnXjtUZksLaZoTf4JHVFuJnlQsxl6UK2nTM.

